In [4]:
import torch

torch.__version__

'1.5.0'

In [8]:
x = torch.empty(5, 3)

print(x)
print(x.dtype)

tensor([[ 3.4732e-37,  0.0000e+00,  3.3987e-37],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00],
        [ 1.5835e-43,  0.0000e+00,  3.3985e-37],
        [ 0.0000e+00, -2.0573e+36,  4.5560e-41],
        [ 9.4404e+29,  4.5560e-41,  9.4406e+29]])
torch.float32


In [16]:
x2 = torch.tensor([5.5, 3], dtype=torch.int)
y2 = torch.tensor([4, 1], dtype=torch.int)
print(x2 + y2)

result = torch.empty(5, 3)
torch.add(x2, y2, out=result)
print(result)

tensor([9, 4], dtype=torch.int32)
tensor([9., 4.])


In [20]:
y2.add_(y2) # Equivalente a x += 2

tensor([64, 16], dtype=torch.int32)

### Resizing

In [26]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())
print(z)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.0570,  1.5912,  0.5292, -0.2286,  1.9251, -0.2095, -1.1696, -0.1695],
        [ 0.1365,  0.4020, -1.6944,  0.5568, -1.7309, -0.6517,  0.6994, -0.6758]])


### Get an item from tensor

In [32]:
x2[0].item()

5

### Convert to Numpy

In [33]:
x.numpy()

array([[ 1.0570153 ,  1.5912387 ,  0.52920955, -0.22861277],
       [ 1.9250879 , -0.20954353, -1.1695515 , -0.16948052],
       [ 0.13647132,  0.40204805, -1.6944486 ,  0.5568306 ],
       [-1.7309216 , -0.65168667,  0.6994389 , -0.67583096]],
      dtype=float32)

In [36]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


In [38]:
a.add_(1)
print(a)
print(b)

tensor([3., 3., 3., 3., 3.])
[3. 3. 3. 3. 3.]


Modifying a tensor also modifies the variable in numpy version